using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class RandomName : MonoBehaviour
{
    private static int _nameIndex = 0;
    
    private static List<string> _names = new List<string>
    {
        "Zorblax",
        "Quilthorn",
        "Grimblix",
        "Snarfle",
        "Wispwraith",
        "Gloomfang",
        "Flutterwisp",
        "Zephyrback",
        "Thornbeast",
        "Lumisprite",
        "Blazehound",
        "Driftclaw",
        "Shardshimmer",
        "Shadowlurk",
        "Frostbite",
        "Quickscale",
        "Emberflame",
        "Moonwhisper",
        "Starblossom",
        "Thunderstrike",
        "Duskbane",
        "Starchaser",
        "Aquashade",
        "Nightshade",
        "Ironjaw",
        "Stormwing",
        "Webweaver",
        "Whisperwind",
        "Scalethorn",
        "Mireclaw",
        "Flamestalker",
        "Glimmerwing",
        "Feralclaw",
        "Frostsaber",
        "Voidprowler",
        "Thornscale",
        "Shadowstrike",
        "Drakescale",
        "Radiantwing",
        "Frostfang",
        "Celestialis",
        "Venomtail",
        "Emberclaw",
        "Serpentis",
        "Bloodmoon",
        "Sablewind",
        "Thunderclaw",
        "Grimshade",
        "Stormcrusher",
        "Swiftshadow",
        "Frostwhisper",
        "Thornfang",
        "Whisperthorn",
        "Ashenclaw",
        "Moonfire",
        "Shimmerwing",
        "Dreadscale",
        "Azureflame",
        "Steelclaw",
        "Stormrider",
        "Venomspine",
        "Frostnova",
        "Gloomstrike",
        "Swiftwing",
        "Blazewing",
        "Shadowclaw",
        "Nightfire",
        "Thunderbeak",
        "Crystalis",
        "Emberfang",
        "Quicksilver",
        "Ironhide",
        "Ashenfang",
        "Moonshadow",
        "Stormblade",
        "Frostwind",
        "Shadowfang",
        "Thornheart",
        "Duskclaw",
        "Serpentshade",
        "Flamebreeze",
        "Thunderstrike",
        "Glimmerclaw",
        "Frostscale",
        "Shadowstalker",
        "Radiantclaw",
        "Emberstrike",
        "Voidwing",
        "Bloodshadow",
        "Whisperfire",
        "Stormscale",
        "Swiftclaw",
        "Frostflame",
        "Celestialwing",
        "Venomstrike",
        "Thunderwing",
        "Steelclaw",
        "Stormfire",
        "Gloomfang",
        "Blazeclaw"
    };

    public static string GetRandomName()
    {
        string n = _names[_nameIndex];
        _nameIndex++;
        return n;
    }
}
